name: Update readme

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Check directory structure
      run: |
        pwd
        ls -R
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode
    
    - name: Set execute permission for update.py
      run: chmod +x update.py
    
    - name: Run update.py
      run: python -u update.py
    
    - name: Check for errors
      if: failure()
      run: |
        echo "Error occurred during script execution"
        exit 1
    
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -am "auto update README.md"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
