name: Update readme

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # actions/checkout 최신 버전 사용
    - name: Set up Python 3.10
      uses: actions/setup-python@v4 # actions/setup-python 최신 버전 사용
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode
    - name: Run update.py
      run: |
        python coding_practice/update.py
    - name: Commit changes
      run: |
        git config --global user.name 'cumulus308'
        git config --global user.email 'rhrudals312@naver.com'
        git add -A
        git commit -am "auto update README.md"
    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
