name: Update readme
on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5  # v5로 업데이트
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode
    - name: Run update.py
      run: |
        pwd
        ls -R
        echo "Current directory contents:"
        ls
        echo "Searching for update.py:"
        find . -name update.py
      continue-on-error: true  # 스크립트 실행 중 오류가 발생해도 계속 진행
    - name: Check for errors
      run: |
        if [ $? -ne 0 ]; then
          echo "Error occurred during script execution"
          exit 1
        fi
    - name: Commit changes
      run: |
        git config --global user.name 'cumulus308'
        git config --global user.email 'rhrudals312@naver.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -am "auto update README.md"
    - name: Push changes
      run: |
        git push
