name: Update readme

on: 
  push:
    branches: [ "main" ]
  pull_request:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10 
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode 
    - name: Run update.py
      run: |
        cd coding_practice
        python update.py
    - name: Commit changes
      run: |
        git config --global user.name 'cumulus308'
        git config --global user.email 'rhrudals312@naver.com'
        git add README.md
        git commit -m "auto update README.md" || echo "No changes to commit"
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
