name: Update readme # 워크플로우의 이름을 지정

on:
  push:
    branches: [ "main" ] # main 브랜치에 push 이벤트가 발생할 때 트리거
  pull_request: # 풀 리퀘스트가 열리거나 변경될 때 트리거

permissions:
  contents: write # 콘텐츠에 대한 쓰기 권한을 설정

jobs:
  build:
    runs-on: ubuntu-latest # 최신 Ubuntu 환경에서 실행
    steps:
    - uses: actions/checkout@v4 # 코드 체크아웃
    - name: Set up Python 3.10
      uses: actions/setup-python@v5 # Python 3.10 설정
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip # pip 업그레이드
    
    - name: Set execute permission for update.py
      run: chmod +x update.py # update.py 파일에 실행 권한 부여
    
    - name: Run update.py
      run: python -u update.py # update.py 실행
    
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Action' # git 사용자 이름 설정
        git config --global user.email 'action@github.com' # git 사용자 이메일 설정
        git add -A # 모든 변경 사항 추가
        git diff --quiet && git diff --staged --quiet || git commit -am "auto update README.md" # 변경 사항이 있을 경우 커밋
    
    - name: Push changes
      uses: ad-m/github-push-action@master # 변경 사항을 원격 저장소에 푸시
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub 토큰 사용
