name: Update readme
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-leetcode
    
    - name: Debug information
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -R
        echo "Python version:"
        python --version
    
    - name: Set execute permission for update.py
      run: chmod +x coding_practice/update.py
    
    - name: Run update.py
      run: |
        pwd
        ls -R
        python update.py
      working-directory: ./coding_practice
    
    - name: Check for errors
      if: failure()
      run: |
        echo "Error occurred during script execution"
        exit 1
    
    - name: Commit changes
      run: |
        git config --global user.name 'cumulus308'
        git config --global user.email 'rhrudals312@naver.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -am "auto update README.md"
    
    - name: Push changes
      run: |
        git push
